# Generated by Django 3.0.4 on 2020-04-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_region_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region_data',
        ),
    ]
