# Generated by Django 3.0.4 on 2020-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_value', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('recovery', models.CharField(max_length=54)),
                ('confirm', models.CharField(max_length=50)),
                ('death', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
